services:
  - type: web
    plan: free
    name: myproj
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4